//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.SqlServer;

    [DbConfigurationType(typeof(DBContextConfig))]
    public partial class WebapiDBEntities : DbContext
    {
        public WebapiDBEntities()
            : base("name=WebapiDBEntities")
        {
        }

        public WebapiDBEntities(string connectionString)
    : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
    }

    public class DBContextConfig : DbConfiguration
    {
        public DBContextConfig()
        {
            SetProviderServices("System.Data.EntityClient", SqlProviderServices.Instance);
            SetDefaultConnectionFactory(new SqlConnectionFactory());
        }
    }
}
