//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CutomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phonenumber { get; set; }
        public string TransactionID { get; set; }
        public string AgentID { get; set; }
    }
}
